# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87e76f11b583c711f5f07ff328e61067c94d7af9210b9bc010a70543165a64d59b6223fd7ffe9a64cfe62d5505d39a54d018faf3ad991cd70de7155c09d11446

test:
  secret_key_base: f7098dd224ff74671e7835a1ab423dd1e1d53acb107b1e97b378f0fb2a883955a5c6fcd5dcbc13c67e95a14c6bf904e743dd589194d89eba002577e9c4669c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
